docs: Add cuda 12.5 to README.md (updated).
abetlen/llama-cpp-python pull request #1791
Opened 2024-10-09 20:14 UTC by Victoran0

Under the Chat Completion section, about the fourth line under it, we have: 'The model will will format the messages into a single prompt using the following order of precedence:'... 
'will' appeared twice, this update fix that.

2024-10-14 12:50 UTC, lukestanley requested changes
The commit message / PR title could better match what it is! Deleting the typo / grammar issue has nothing to do with cuda.

2024-10-15 21:20 UTC, Victoran0 commented
> The commit message / PR title could better match what it is! Deleting the typo / grammar issue has nothing to do with cuda.

Oops, sorry about that, I did use the same message as the latest commit the readme.md file has, with the additional (updated) at the end. That is because i thought the new commit is not a new feature, only fixing a typographical error.
However, I have edited the commit message in a new commit.

2024-10-17 15:32 UTC, lukestanley commented
But now there are 2 commit messages and none of them quite describe what someone would want to know. For example if someone saw the message: "Typo at line 340 fixed", they would think - what file? Then they might go to check the file and see that there is no change there at all. Empty commits are not so helpful.
Instead, you might want to undo your last empty commit, and adjusting the commit message in your original commit.
You would probably then want to force push it up to overwrite Victoran0:patch-2 with a better commit message.
ChatGPT (among other chatbots) is probably good at helping with this sort of thing.

2024-10-18 00:55 UTC, Victoran0 commented
@lukestanley how does it look now?

2024-10-18 08:10 UTC, lukestanley approved these changes
It's readable, it matches up with what it does. I think it's acceptable. There is no need to say the line number, but it's okay. It's fairly clean and tidy. In my capacity as a random internet person I approve. :+1:

2024-10-18 16:38 UTC, Victoran0 commented
Am glad you considered 👏👏👏

2026-06-01 02:11 UTC, merged