Create simple_local_chat.py
abetlen/llama-cpp-python pull request #575
Opened 2023-08-05 19:31 UTC by Mrgithub93

easy to use high level chat script

2023-08-06 09:23 UTC, bretello requested changes

2023-08-06 09:23 UTC, bretello commented on examples/high_level_api/simple_local_chat.py
> +parser.add_argument("-m", "--model", "--interactive", type=str, default="<your path to your ggml-model.bin>")
Why `--interactive`?

2023-08-06 09:23 UTC, bretello commented on examples/high_level_api/simple_local_chat.py
> +    ChatCompletionMessage(role='user', content='Hello)
Missing end single quote `'`

2023-08-06 10:24 UTC, Mrgithub93 commented on examples/high_level_api/simple_local_chat.py
> +parser.add_argument("-m", "--model", "--interactive", type=str, default="<your path to your ggml-model.bin>")
Damn, forgot that one

2023-08-06 10:27 UTC, Mrgithub93 commented on examples/high_level_api/simple_local_chat.py
> +    ChatCompletionMessage(role='user', content='Hello)
Wtf

2023-10-03 17:18 UTC, delock commented
Hi, thanks for this example!

When I keep talking with it I got this error, is there a way to avoid this error?
```
ValueError: Requested tokens (527) exceed context window of 512
```

2026-06-01 04:31 UTC, closed without merging